# Generated by Django 3.1.4 on 2021-01-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20210129_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number_apartment',
            field=models.IntegerField(null=True),
        ),
    ]
